[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/api/:splat"
  status = 200
  force = true
  conditions = {Country = ["US"]}

[build.environment]
  REACT_APP_API_URL = "https://seu-backend-url.herokuapp.com/api"